version: '3.8'
services:
  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=rugal
      - POSTGRES_PASSWORD=rugal12345
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5444:5432'
volumes:
  postgres: